# Cloud Build configuration for backend deployment
steps:
  # Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/shuffle-and-sync-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/shuffle-and-sync-backend:latest'
      - '.'
    id: 'build-backend'

  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/shuffle-and-sync-backend:$COMMIT_SHA'
    id: 'push-backend'
    waitFor: ['build-backend']

  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'gcr.io/$PROJECT_ID/shuffle-and-sync-backend:latest'
    id: 'push-backend-latest'
    waitFor: ['build-backend']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/shuffle-and-sync-backend:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - '${_REGION}'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      # Add startup probe for initialization grace period
      # This gives the container up to 4 minutes to complete initialization
      # while responding to health checks
      - '--no-cpu-throttling'
    id: 'deploy-backend'
    waitFor: ['push-backend']

# Configure build timeout
timeout: 1200s

# Configure build options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Substitutions for variables
# These provide default values that can be overridden with --substitutions flag
# Example: gcloud builds submit --config cloudbuild.yaml --substitutions=_REGION=us-east1
substitutions:
  _REGION: us-central1
  _SERVICE_NAME: shuffle-and-sync-backend

images:
  - 'gcr.io/$PROJECT_ID/shuffle-and-sync-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/shuffle-and-sync-backend:latest'