name: Code Formatting Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  prettier:
    name: Check Prettier Formatting
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      
      - name: Check code formatting
        run: npm run format:check
      
      - name: Report formatting issues
        if: failure()
        run: |
          echo "❌ Code formatting check failed!"
          echo ""
          echo "Some files are not formatted according to Prettier standards."
          echo ""
          echo "To fix locally, run:"
          echo "  npm run format"
          echo ""
          echo "Then commit and push the changes."
          echo ""
          echo "See FORMATTING.md for more information."
          exit 1
